### ISSUE TITLE
"error in system2"

### ISSUE THREAD

**Issue by scarlett** [Hemken/SASmarkdown#22] opened 2022-10-21 18:30 UTC
Hello, 

Thanks so much for building this amazing package. I encountered an issue running the first SAS chunk after installation, the full message is copied below. Looking forward to resolving this issue and exploring the full power of the package! Thanks in advance for your help.

I tried installing SASmarkdown using install.packages("SASmarkdown) and devtools::install_github("Hemken/SASmarkdown"). Both installations seem successful - I saw the correct message 
"library(SASmarkdown)
SAS found at C:/Program Files/SASHome/SASFoundation/9.4/sas.exe
SAS engines are now ready to use."

However, when I run the testing code below, it gives me the system2 error.
```{sas} 
proc means data=sashelp.class;
run;
```
"running: C:/Program Files/SASHome/SASFoundation/9.4/sas.exe sas2fe02fcf776f.sas -nosplash -linesize 75
Error in system2(cmd, code, stdout = TRUE, stderr = TRUE, env = options$engine.env) : 
  'CreateProcess' failed to run 'C:\PROGRA~1\SASHome\SASFOU~1\9.4\sas.exe sas2fe02fcf776f.sas -nosplash -linesize 75'"

**Comment by pdiff** [comment] 2022-10-21 22:53
I get this as well. I have four separate SAS code chunks. The first two run fine, but the last two throw this error. Setting error=TRUE in each chunk is a work around and the code will render, substituting the log for the code in the html, but it is a pain. Other than the log in the resulting html, everything else (Proc Glimmix and Proc Sgplot) runs and displays fine from RStudio. I've tried grabbing the corresponding generated SAS files and running them in batch mode. They have no errors and run as expected.

**Comment by Hemken** [comment] 2022-10-21 23:22
Scarlet, what version of R and what version of the rmarkdown package are you using?

Pdiff, can you send me the source and final document?
________________________________

**Comment by pdiff** [comment] 2022-10-22 01:23
Will do, but not until Monday. I don’t have access here at home.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Hemken** [comment] 2022-10-22 13:20
Scarlett,

What happens when you run this R code (not in a markdown document)?

cmd <- "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"

code <- "test.sas"
writeLines(c("proc means data=sashelp.class;", "run;"), con=code)

system2(cmd, code, stdout = TRUE, stderr = TRUE)
readLines("test.lst")

codeplus <- paste(code, "-nosplash -linesize 75")
system2(cmd, codeplus, stdout = TRUE, stderr = TRUE)
readLines("test.lst")

--
Doug Hemken
Statistical consultant
4226I Social Science Bldg.

***@***.***
608-262-4327

To make a consulting appointment send me an email, or use the on-line scheduler:
https://doodle.com/mm/doughemken/book-a-time

From: Scarlett Wang ***@***.***>
Sent: Friday, October 21, 2022 1:31 PM
To: Hemken/SASmarkdown ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hemken/SASmarkdown] "error in system2" (Issue #22)


Hello,

Thanks so much for building this amazing package. I encountered an issue running the first SAS chunk after installation, the full message is copied below. Looking forward to resolving this issue and exploring the full power of the package! Thanks in advance for your help.

I tried installing SASmarkdown using install.packages("SASmarkdown) and devtools::install_github("Hemken/SASmarkdown"). Both installations seem successful - I saw the correct message
"library(SASmarkdown)
SAS found at C:/Program Files/SASHome/SASFoundation/9.4/sas.exe
SAS engines are now ready to use."

However, when I run the testing code below, it gives me the system2 error.

proc means data=sashelp.class;

run;

"running: C:/Program Files/SASHome/SASFoundation/9.4/sas.exe sas2fe02fcf776f.sas -nosplash -linesize 75
Error in system2(cmd, code, stdout = TRUE, stderr = TRUE, env = options$engine.env) :
'CreateProcess' failed to run 'C:\PROGRA1\SASHome\SASFOU1\9.4\sas.exe sas2fe02fcf776f.sas -nosplash -linesize 75'"

**Comment by pdiff** [comment] 2022-10-24 17:11
Doug,
              Attached are the requested files. I’ve also added the text of the Rstudio render window I get, as well as a CSS file I include (ripped from SAS output) to get table formatting I want. Chunks 1-4 run with no issues. Chunks 5 and 6 must be run with the ERROR=TRUE option to render in the final html.

Thank you for looking into this. Let me know if there is more information I can provide.

Bill

BILL PRICE
Director

College of Agricultural and Life Sciences
Statistical Programs
Office: 307, AgSci
***@***.******@***.***>
www.uidaho.edu/cals/statistical-programs<https://www.uidaho.edu/cals/statistical-programs>
www.agstats.io
208-885-5930

[University of Idaho]

**Comment by Hemken** [comment] 2022-10-24 17:35
Bill, I got the knitr log, but I guess I don’t know how to get attachments through Github.  Could you send those files to me directly?

***@***.***

**Comment by pdiff** [comment] 2022-10-24 17:50
Sorry. I used my email to reply, not Github. Github won't let me drop these file types here, but here is a [dropbox link](https://www.dropbox.com/sh/900upmg22m4q8ut/AABCdcWWXGNFSnUKO7RvfC8va?dl=0)

**Comment by Hemken** [comment] 2022-10-24 17:56
Got them

**Comment by Hemken** [comment] 2022-10-24 18:33
Thanks for including the data!

I notice you are using an older style of specifying chunk options.  A quick fix seems to be working with the "new" style (actually, this is a couple of years old by now).

So instead of

````
```{r include=FALSE}
require(SASmarkdown)

saspath <- "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"

sasopts <- "-nosplash -ls 200  "
```
````
I would set up with

````
```{r  setup, include=FALSE}
require(SASmarkdown)
sasopts <- "-nosplash -ls 200  "
knitr::opts_chunk$set(engine.opts=list(sashtml=sasopts, sashtmllog=sasopts),
                      comment=NA)
```
````

and in later chunks, instead of

````
```{r Logistic1, engine="sashtml", collectcode=TRUE, engine.path=saspath, include=TRUE, engine.opts=sasopts, comment="", error=TRUE}
* whatever;
```
````

I would use

````
```{sashtml Logistic1}
* whatever;
```
````

You also don't need to accumulate all that code with collectcode=TRUE.  You only need that for your DATA step.

[testdh.Rmd.txt](https://github.com/Hemken/SASmarkdown/files/9854291/testdh.Rmd.txt)

**Comment by scarlett** [comment] 2022-10-24 18:50
Hi Hemken,

Thanks so much for your prompt reply! I use 4.2.1 base R, 2.17 rmarkdown,
and 1.40 knitr

I ran the codes you suggested in a script and got similar error messages
[image: image.png]

**Comment by Hemken** [comment] 2022-10-24 18:59
Scarlett, I do not see an image.  Could you upload your screenshot to Github, or better, copy and paste the text?

Can you send me your source document?  To upload it to Github, you will have to save it with a “.txt” file extension instead of “.rmd”.

**Comment by scarlett** [comment] 2022-10-24 19:06
Sure! Attached is the source document, and the testing code/error copied below. 


> cmd <- "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"
> code <- "test.sas"
> writeLines(c("proc means data=sashelp.class;", "run;"), con=code)
> system2(cmd, code, stdout = TRUE, stderr = TRUE)
Error in system2(cmd, code, stdout = TRUE, stderr = TRUE) : 
  'CreateProcess' failed to run 'C:\PROGRA~1\SASHome\SASFOU~1\9.4\sas.exe test.sas'
> readLines("test.lst")
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") : cannot open file 'test.lst': No such file or directory
> codeplus <- paste(code, "-nosplash -linesize 75")
> system2(cmd, codeplus, stdout = TRUE, stderr = TRUE)
Error in system2(cmd, codeplus, stdout = TRUE, stderr = TRUE) : 
  'CreateProcess' failed to run 'C:\PROGRA~1\SASHome\SASFOU~1\9.4\sas.exe test.sas -nosplash -linesize 75'
> readLines("test.lst")
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") : cannot open file 'test.lst': No such file or dir
[sas test.txt](https://github.com/Hemken/SASmarkdown/files/9854581/sas.test.txt)
ectory

**Comment by pdiff** [comment] 2022-10-24 19:14
> Thanks for including the data!
> 
> I notice you are using an older style of specifying chunk options. A quick fix seems to be working with the "new" style (actually, this is a couple of years old by now).
> 
> So instead of
> 
> ```
> ```{r include=FALSE}
> require(SASmarkdown)
> 
> saspath <- "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"
> 
> sasopts <- "-nosplash -ls 200  "
> ```
> ```
> 
> I would set up with
> 
> ```
> ```{r  setup, include=FALSE}
> require(SASmarkdown)
> sasopts <- "-nosplash -ls 200  "
> knitr::opts_chunk$set(engine.opts=list(sashtml=sasopts, sashtmllog=sasopts),
>                       comment=NA)
> ```
> ```
> 
> and in later chunks, instead of
> 
> ```
> ```{r Logistic1, engine="sashtml", collectcode=TRUE, engine.path=saspath, include=TRUE, engine.opts=sasopts, comment="", error=TRUE}
> * whatever;
> ```
> ```
> 
> I would use
> 
> ```
> ```{sashtml Logistic1}
> * whatever;
> ```
> ```
> 
> You also don't need to accumulate all that code with collectcode=TRUE. You only need that for your DATA step.
> 
> [testdh.Rmd.txt](https://github.com/Hemken/SASmarkdown/files/9854291/testdh.Rmd.txt)

Perfect. Thank you, and thank you for the package. It has been very helpful. I guess I picked that legacy code up from an old web page and, yes, the collect codes were there as I was trying to debug some things.

Thanks again and for the quick response.

Bill

**Comment by Hemken** [comment] 2022-10-24 19:18
I’ve actually further narrowed it down to the “collectcode = TRUE” in the second SAS chunk.  None of the other changes I made mattered!  (but I still recommend them)

**Comment by Hemken** [comment] 2022-10-24 19:32
Scarlett, your code runs for me, although with a warning that you try to make “sashtml” the default engine before it has been defined (i.e. before you load the SASmarkdown package).

I do not reproduce your error message.

What version of the Windows operating system are you using?  What version of SAS do you have, and where is it actually installed?

**Comment by Hemken** [comment] 2022-10-24 19:39
Revised version of Scarlett's code that works for me:

[sas_test.Rmd.txt](https://github.com/Hemken/SASmarkdown/files/9854809/sas_test.Rmd.txt)

**Comment by scarlett** [comment] 2022-10-24 19:46
Ahh that's interesting. I use windows server 2016 standard version 1607. SAS is 9.4 (TS1M7), which is installed C:\Program Files\SASHome. A colleage of mine uses a clone of my VM and could install and use the package.

**Comment by Hemken** [comment] 2022-10-24 20:05
I’m also on a Windows server, running as a VM, and using SAS 9.4 TS1M7.

**Comment by scarlett** [comment] 2022-10-24 20:14
I'm using the newest version of RStudio. Could that be the problem?

RStudio 2022.07.1+554 "Spotted Wakerobin" Release
(7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

**Comment by Hemken** [comment] 2022-10-24 21:47
Seems unlikely that is the problem, but I'll give it a try.  The message suggests the SAS executable is not where we think it should be.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Hemken** [comment] 2022-10-25 11:50
More on Bill's "error in system2":

The `collectcode` captured a call to ODS graphics, the `plots` option in a `PROC FREQ`.  This requires an explicit `ODS GRAPHICS ON;` when included in a `collectcode` (or when using the plain `sas` knitr engine).

I find it curious that `PROC SGPLOT` does not produce the same error when collected - I thought this too was ods graphics.

**Comment by Hemken** [comment] 2022-10-25 13:50
Scarlett,

That is the same version of RStudio I have been using.

Can you please verify the location of the SAS executable?  Launch SAS, then run

```
%put %sysget(SASROOT);
```

**Comment by pdiff** [comment] 2022-10-25 15:55
> More on Bill's "error in system2":
> 
> The `collectcode` captured a call to ODS graphics, the `plots` option in a `PROC FREQ`. This requires an explicit `ODS GRAPHICS ON;` when included in a `collectcode` (or when using the plain `sas` knitr engine).
> 
> I find it curious that `PROC SGPLOT` does not produce the same error when collected - I thought this too was ods graphics.

Hmmm, I had thought of this too (thought I had tried the ODS Graphics On command), but dismissed it when the sgplot did not have similar issues.  Glad you narrowed this down.

I'll never understand why SAS didn't just implement markdown features as part of ODS anyway. It's 90% there.

**Comment by Hemken** [comment] 2022-10-31 11:21
Scarlett, did you try anything else?

--
Doug Hemken
SSCC statistical consultant
4226i Social Science Bldg.

**Comment by scarlett** [comment] 2022-11-02 16:40
Thanks for following up, Doug! I got in touch with SAS support since it
looks like it could be an installation issue. We also have other symptoms -
double clicking .sas file doesn't work  Will try SASmarkdown again after
troubleshooting with SAS support.

**Comment by Hemken** [comment] 2022-12-01 13:12
No follow up from Scarlett.

**Closed as completed by Hemken** 2022-12-01 13:12 UTC
