### ISSUE TITLE
Object out.log not found

### ISSUE THREAD

**Issue by jmkurka83** [Hemken/SASmarkdown#16] opened 2021-05-18 21:43 UTC
It seems I've successfully installed the package, but keep getting an error when testing. I've searched online but have not found a solution that works.
Here is my code when testing:
> knitr::opts_chunk$set(echo = TRUE)
> library(SASmarkdown)
package �SASmarkdown� was built under R version 4.0.5sas, saslog, sashtml, and sashtmllog engines
   are now ready to use.

````{sas sas-ex Import, echo=TRUE, error=TRUE}
proc means data=sashelp.class (keep = age);
run ;
````
Here is resulting error:
`Error in knitrEngine(mergedOptions) : object 'out.log' not found`

**Comment by Hemken** [comment] 2021-05-18 22:00
Can you tell me what version of R and what version of the knitr package you are using?

________________________________
From: Jonathan Kurka ***@***.***>
Sent: Tuesday, May 18, 2021 4:43:28 PM
To: Hemken/SASmarkdown ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hemken/SASmarkdown] Object out.log not found (#16)


It seems I've successfully installed the package, but keep getting an error when testing. I've searched online but have not found a solution that works.
Here is my code when testing:
`> knitr::opts_chunk$set(echo = TRUE)

library(SASmarkdown)
package �SASmarkdown� was built under R version 4.0.5sas, saslog, sashtml, and sashtmllog engines
are now ready to use.'

proc means data=sashelp.class (keep = age);

run ;



Here is resulting error:
`Error in knitrEngine(mergedOptions) : object 'out.log' not found``

**Comment by jmkurka83** [comment] 2021-05-18 22:02
Sure! 
R version 4.0.3
knitr version 1.3.1

**Comment by Hemken** [comment] 2021-05-20 11:34
I am not able to reproduce this error.  Which version of SASmarkdown are you using?  You can use `packageVersion(“SASmarkdown”)`.

Can you email me your complete rmarkdown document at ***@***.******@***.***> ?

From: Jonathan Kurka ***@***.***>
Sent: Tuesday, May 18, 2021 4:43 PM
To: Hemken/SASmarkdown ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hemken/SASmarkdown] Object out.log not found (#16)


It seems I've successfully installed the package, but keep getting an error when testing. I've searched online but have not found a solution that works.
Here is my code when testing:
`> knitr::opts_chunk$set(echo = TRUE)

library(SASmarkdown)
package �SASmarkdown� was built under R version 4.0.5sas, saslog, sashtml, and sashtmllog engines
are now ready to use.'

proc means data=sashelp.class (keep = age);



run ;



Here is resulting error:
`Error in knitrEngine(mergedOptions) : object 'out.log' not found``

**Comment by jmkurka83** [comment] 2021-05-20 19:45
Hi Doug,

Sure. It looks like I’m using 0.4.3. Let me know if this isn’t what you’re looking for or if there’s anything I need to do on my end.

Thanks!


Jonathan M. Kurka, PhD, EP-C, CES

Senior Research Analyst, Biostatistics Core

Arizona State University | College of Health Solutions

550 N 3rd Street, Phoenix, AZ 85004 | Mercado C324

602-496-1608 | ***@***.*** | chs.asu.edu<https://chs.asu.edu/>

-- For REDCap assistance and questions, please refer to the help_redcap<https://asuchs.slack.com/messages/CMR0KM6P2> Slack channel

**Comment by Hemken** [comment] 2021-05-20 19:49
Are you able to reinstall from GitHub?  It seems I need to update my instructions

________________________________

**Comment by jmkurka83** [comment] 2021-05-20 20:10
I uninstalled the CRAN installation and installed the zip downloaded from GitHub. Now am receiving this:

running:  sas4c6866b93567.sas
Error in knitrEngine(mergedOptions) : object 'out.log' not found
Warning in unlink(c(logf, listf, f)) :
  cannot get info on 'sas4c6866b93567.sas', reason 'Access is denied'

**Comment by jmkurka83** [comment] 2021-05-20 20:24
Success! I removed the package, installed devtools, installed SASmarkdown via devtools and now functioning

**Comment by fenguoerbian** [comment] 2022-07-07 01:54
Hi, I'm facing the same error here when rendering the following Rmd file.

```
    ---
    title: "testsas"
    date: '2022-07-07'
    output: html_document
    ---

    ```{r setup, include=FALSE}
    library(SASmarkdown)
    ```
    ```{sas example1}
    proc means data=sashelp.class (keep = age);
    run;
    ```
```

Hitting `knit` button the `example1` code chunk reports the error

```
running:  sas3eb0165819a5.sas -nosplash -ls 75
Error in knitrEngine(mergedOptions) : object 'out.log' not found
```

Is there any additinonal settings that I missed?

My `sessioninfo::session_info()` is 

- Session info ------------------------------------------------------
 setting  value
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    C
 tz       Asia/Taipei
 date     2022-07-07
 rstudio  2022.02.3+492 Prairie Trillium (desktop)
 pandoc   2.17.1.1 @ C:/R/RStudio/bin/quarto/bin/ (via rmarkdown)

- Packages ----------------------------------------------------------
 package     * version date (UTC) lib source
 bslib         0.3.1   2021-10-06 [1] CRAN (R 4.2.1)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.2.1)
 cli           3.3.0   2022-04-25 [1] CRAN (R 4.2.1)
 crayon        1.5.1   2022-03-26 [1] CRAN (R 4.2.1)
 curl          4.3.2   2021-06-23 [1] CRAN (R 4.2.1)
 digest        0.6.29  2021-12-01 [1] CRAN (R 4.2.1)
 evaluate      0.15    2022-02-18 [1] CRAN (R 4.2.1)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.1)
 htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.2.1)
 jquerylib     0.1.4   2021-04-26 [1] CRAN (R 4.2.1)
 jsonlite      1.8.0   2022-02-22 [1] CRAN (R 4.2.1)
 knitr         1.39    2022-04-26 [1] CRAN (R 4.2.1)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.1)
 pkgbuild      1.3.1   2021-12-20 [1] CRAN (R 4.2.1)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.2.1)
 processx      3.6.1   2022-06-17 [1] CRAN (R 4.2.1)
 ps            1.7.1   2022-06-18 [1] CRAN (R 4.2.1)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.1)
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.2.1)
 rlang         1.0.3   2022-06-27 [1] CRAN (R 4.2.1)
 rmarkdown     2.14    2022-04-25 [1] CRAN (R 4.2.1)
 rprojroot     2.0.3   2022-04-02 [1] CRAN (R 4.2.1)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.2.1)
 SASmarkdown * 0.5.3   2022-07-07 [1] Github (Hemken/SASmarkdown@54d6140)
 sass          0.4.1   2022-03-23 [1] CRAN (R 4.2.1)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.1)
 stringi       1.7.6   2021-11-29 [1] CRAN (R 4.2.0)
 stringr       1.4.0   2019-02-10 [1] CRAN (R 4.2.1)
 withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.1)
 xfun          0.31    2022-05-10 [1] CRAN (R 4.2.1)
 yaml          2.3.5   2022-02-21 [1] CRAN (R 4.2.0)

 [1] C:/R/MyLibrary
 [2] C:/R/R-4.2.1/library

---------------------------------------------------------------------

**Comment by Hemken** [comment] 2022-08-17 19:21
There are two ways to get this error message, "object outlog not found".  One is if SAS fails to run - you may not have specified the executable path correctly, or you may have SAS command line options that are incorrect.

Another way to get this error message is if SAS writes it's output to a folder other than where the document source (the RMD file) is located - you might have either SAS or knitr configured to use a specific folder?

**Closed as completed by Hemken** 2022-08-17 19:21 UTC
